server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/mime.types;

  # Support proper byte-range requests for videos
  location ~ \.(mp4|webm|ogv)$ {
    try_files $uri =404;
    add_header Accept-Ranges bytes;
  }

  location ~ ^/\.well-known/(apple-app-site-association|assetlinks\.json)$ {
    default_type application/json;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}