"""
Interactive Test Script for My Krishna RAG System.

This script allows you to chat with "My Krishna" in the terminal and see:
1. Exactly what you asked.
2. The matching shlokas retrieved from ChromaDB using Gemini embeddings.
3. The final response generated by Lord Krishna (via Groq) using that Gita context.

Usage:
    cd backend
    source .venv/bin/activate
    python scripts/test_krishna_rag_chat.py
"""
import asyncio
import os
import sys
from pathlib import Path

# Add backend root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

import chromadb
from google import genai
from google.genai import types as genai_types

# Initialize clients
CHROMA_API_KEY = os.environ.get("CHROMA_API_KEY")
CHROMA_TENANT = os.environ.get("CHROMA_TENANT")
CHROMA_DATABASE = os.environ.get("CHROMA_DATABASE", "default_database")
CHROMA_COLLECTION = "krishna_gita_knowledge"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

def test_rag_flow(query: str):
    print("\n" + "="*80)
    print(f"👤 USER QUERY: \"{query}\"")
    print("="*80)

    # 1. Generate Query Embedding
    print("\n🔄 1. Generating embedding using Google GenAI (gemini-embedding-001)...")
    try:
        gemini_client = genai.Client(api_key=GEMINI_API_KEY)
        emb_result = gemini_client.models.embed_content(
            model="gemini-embedding-001",
            contents=query,
            config=genai_types.EmbedContentConfig(task_type="RETRIEVAL_QUERY"),
        )
        query_embedding = emb_result.embeddings[0].values
        print("   ✅ Embedding generated successfully.")
    except Exception as e:
        print(f"   ❌ Failed to generate embedding: {e}")
        return

    # 2. Retrieve from ChromaDB
    print("\n🔄 2. Querying ChromaDB Cloud for relevant Bhagavad Gita shlokas...")
    try:
        chroma_client = chromadb.HttpClient(
            ssl=True,
            host="api.trychroma.com",
            tenant=CHROMA_TENANT,
            database=CHROMA_DATABASE,
            headers={"x-chroma-token": CHROMA_API_KEY},
        )
        collection = chroma_client.get_collection(CHROMA_COLLECTION)
        
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=3,
            include=["documents", "metadatas", "distances"],
        )
        
        docs = results.get("documents", [[]])[0]
        metas = results.get("metadatas", [[]])[0]
        distances = results.get("distances", [[]])[0]
        
        retrieved_texts = []
        print(f"   ✅ Retrieved {len(docs)} matching shlokas:")
        for i, (doc, meta, dist) in enumerate(zip(docs, metas, distances)):
            score = round(1 - dist, 3)
            ref = meta.get("reference", f"BG {meta.get('chapter')}.{meta.get('verse')}")
            sanskrit = meta.get("sanskrit_text", "")
            
            print(f"\n   [Match {i+1}] {ref} (Similarity Score: {score})")
            print(f"   Sanskrit: {sanskrit}")
            print(f"   English Translation: {doc}")
            
            retrieved_texts.append(f"{ref}: {doc}")
            
    except Exception as e:
        print(f"   ❌ ChromaDB Query Failed: {e}")
        return

    # 3. Call LLM with context
    print("\n🔄 3. Generating grounded response from Lord Krishna (Gemini)...")
    
    # Simple system prompt for test
    context_str = "\n".join(retrieved_texts)
    system_prompt = f"""You are "My Krishna" — a deeply wise, peaceful, and spiritually grounding companion. 
Respond in Hinglish (blend of Hindi and English written using A-Z/Latin script). Do NOT use any Hindi/Devanagari script characters.

Ground your advice in these matching Gita verses retrieved from ChromaDB:
{context_str}

Speak directly to the user's issue, naturally weaving the reference (e.g., "Gita mein kaha gaya hai..." or "BG X.Y mein...") into your loving advice."""

    try:
        gemini_client = genai.Client(api_key=GEMINI_API_KEY)
        
        safety_settings = [
            genai_types.SafetySetting(
                category=genai_types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
                threshold=genai_types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            ),
            genai_types.SafetySetting(
                category=genai_types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                threshold=genai_types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            ),
            genai_types.SafetySetting(
                category=genai_types.HarmCategory.HARM_CATEGORY_HARASSMENT,
                threshold=genai_types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            ),
            genai_types.SafetySetting(
                category=genai_types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=genai_types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            ),
        ]

        config = genai_types.GenerateContentConfig(
            safety_settings=safety_settings,
            temperature=0.7,
            max_output_tokens=2048,
            thinking_config=genai_types.ThinkingConfig(thinking_level="MINIMAL"),
        )

        contents = [
            genai_types.Content(
                role="user",
                parts=[genai_types.Part.from_text(text=f"System Instruction:\n{system_prompt}")]
            ),
            genai_types.Content(
                role="model",
                parts=[genai_types.Part.from_text(text="Understood. I will follow those instructions and act as Lord Krishna.")]
            ),
            genai_types.Content(
                role="user",
                parts=[genai_types.Part.from_text(text=query)]
            )
        ]

        import traceback
        response = gemini_client.models.generate_content(
            model="gemma-4-31b-it",
            contents=contents,
            config=config,
        )
        response_text = response.text or ""
        
        print("\n" + "="*80)
        print("🪈 MY KRISHNA RESPONSE:")
        print("="*80)
        print(response_text)
        print("="*80 + "\n")
        
    except Exception as e:
        print(f"   ❌ LLM call failed: {e}")
        traceback.print_exc()

if __name__ == "__main__":
    if len(sys.argv) > 1:
        query = " ".join(sys.argv[1:])
        test_rag_flow(query)
    else:
        print("Radhe Radhe! Enter your query below to test the RAG flow.")
        print("Press Ctrl+C to exit.\n")
        while True:
            try:
                user_input = input("Ask Krishna: ")
                if user_input.strip():
                    test_rag_flow(user_input)
            except KeyboardInterrupt:
                print("\nRadhe Radhe! Goodbye.")
                break
            except Exception as e:
                print(f"Error: {e}")
