import { StyleSheet, Platform } from 'react-native';
import { SCREEN_WIDTH, PAGE_PADDING, ACTION_CARD_WIDTH, ACTION_CARD_HEIGHT, FEATURE_CARD_WIDTH, FEATURE_CARD_HEIGHT } from './homeConstants';
import { FONTS } from '../../constants/theme';

export const styles = StyleSheet.create({
    notificationDot: {
        position: 'absolute',
        top: 2,
        right: 2,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#FF6A00',
        borderWidth: 1,
        borderColor: '#FFF',
    },
    festivalAlertCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFECD9',
        marginTop: 14,
        borderRadius: 18,
        padding: 14,
        borderWidth: 1,
        borderColor: '#FFD6B0',
    },
    festivalAlertIcon: {
        width: 42,
        height: 42,
        borderRadius: 12,
        backgroundColor: '#FF7A00',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    festivalAlertTextWrapper: {
        flex: 1,
    },
    festivalAlertTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#3B1D07',
        marginBottom: 4,
    },
    festivalAlertSubtitle: {
        fontSize: 12,
        lineHeight: 18,
        color: '#5A432B',
    },
    nameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    liveLocationBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF4ED',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: '#FFD7C2',
    },
    liveLocationText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#FF6B00',
        marginLeft: 2,
        textTransform: 'uppercase',
    },
    screen: {
        flex: 1,
    },
    content: {},
    upperContentWrapper: {
        paddingHorizontal: PAGE_PADDING,
    },
    postBannerSection: {
        width: '100%',
        backgroundColor: 'transparent',
        paddingHorizontal: PAGE_PADDING,
    },
    cardTextureContent: {
        flex: 1,
        zIndex: 1,
        justifyContent: 'space-between',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 2,
        marginTop: Platform.OS === 'android' ? 8 : 0,
        paddingTop: Platform.OS === 'android' ? 4 : 0,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: Platform.OS === 'android' ? undefined : 1,
        marginRight: 10,
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 0,
    },
    headerIconButton: {
        width: Platform.OS === 'android' ? 36 : 40,
        height: Platform.OS === 'android' ? 36 : 40,
        borderRadius: Platform.OS === 'android' ? 18 : 20,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    profileButton: {
        width: Platform.OS === 'android' ? 42 : 55,
        height: Platform.OS === 'android' ? 42 : 55,
        borderRadius: Platform.OS === 'android' ? 21 : 28,
        position: 'relative',
        overflow: 'hidden',
    },
    headerOnlineDot: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#4CAF50',
        borderWidth: 2,
        borderColor: '#FFF',
    },
    sosConcentricWrap: {
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    sosRing: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    greetingBlock: {
        marginLeft: 12,
        flex: 1,
    },
    greeting: {
        color: '#000',
        fontSize: 19,
        fontWeight: '600',
    },
    subGreeting: {
        color: '#000',
        fontSize: 14,
        fontWeight: '600',
        opacity: 0.85,
    },
    bioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    topFeatureRow: {
        flexDirection: 'row',
        marginTop: 12,
        marginBottom: 8,
        gap: 8,
        marginHorizontal: -PAGE_PADDING,
    },
    featureCard: {
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.10)',
        borderRadius: 15,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        width: FEATURE_CARD_WIDTH,
        height: FEATURE_CARD_HEIGHT,
    },
    featureIconWrap: {
        width: 50,
        height: 50,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
    },
    urgentCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#FF4D4D',
        alignItems: 'center',
        justifyContent: 'center',
    },
    urgentExclamation: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '900',
    },
    calendarIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    calendarIconText: {
        position: 'absolute',
        top: 8,
        fontSize: 10,
        fontWeight: '800',
        color: '#000',
    },
    featureTextContainer: {
        flex: 1,
        marginLeft: 8,
        justifyContent: 'center',
    },
    featureTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 13,
        color: '#000',
        lineHeight: 16,
    },
    featureSubtitle: {
        fontFamily: 'Inter_500Medium',
        fontSize: 10,
        color: '#000',
        marginTop: 2,
        lineHeight: 13,
    },
    featuredLiveCard: {
        width: Math.min(375, SCREEN_WIDTH - 2 * PAGE_PADDING),
        height: Platform.OS === 'ios' ? 185 : 160,
        borderRadius: 15,
        overflow: 'hidden',
        marginBottom: 5,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        alignSelf: 'center',
    },
    featuredLiveImage: {
        width: '100%',
        height: '100%',
        borderRadius: 15,
        overflow: 'hidden',
    },
    featuredLiveOverlay: {
        ...StyleSheet.absoluteFillObject,
        padding: 15,
        justifyContent: 'space-between',
        borderRadius: 15,
    },
    liveBadge: {
        alignSelf: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FF0000',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    liveDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#FFF',
    },
    liveBadgeText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: '900',
        marginLeft: 4,
    },
    featuredLiveContent: {
        marginBottom: 25,
    },
    featuredLiveTitle: {
        fontFamily: 'Outfit_700Bold',
        fontSize: 22,
        fontWeight: '900',
        color: '#FFD700',
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    featuredDevotees: {
        fontFamily: 'Outfit_600SemiBold',
        fontSize: 15,
        fontWeight: '700',
        color: '#FFF',
        marginTop: 10,
        marginBottom: 2,
    },
    featuredTime: {
        fontFamily: 'Outfit_500Medium',
        fontSize: 14,
        fontWeight: '800',
        color: '#FFF',
    },
    joinJaapButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FF6A00',
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 999,
        alignSelf: 'flex-start',
        gap: 8,
    },
    playIconContainer: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    joinJaapText: {
        color: '#FFF',
        fontSize: 15,
        fontWeight: '900',
    },
    actionCardsScrollView: {
        marginHorizontal: -PAGE_PADDING,
    },
    actionCardsScroll: {
        paddingHorizontal: PAGE_PADDING,
        paddingTop: 24,
        paddingBottom: 4,
        gap: Platform.OS === 'ios' ? 8 : 10,
    },
    actionCard: {
        width: Platform.OS === 'android' ? undefined : ACTION_CARD_WIDTH,
        height: Platform.OS === 'android' ? undefined : ACTION_CARD_HEIGHT,
        borderRadius: 15,
        padding: 10,
        justifyContent: 'space-between',
        position: 'relative',
        overflow: 'hidden',
    },
    cardHeaderBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.2)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        alignSelf: 'flex-start',
        gap: 4,
    },
    cardHeaderBadgeYellow: {
        backgroundColor: '#FFF5E0',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#FFD6A5',
        zIndex: 100,
        elevation: 5,
    },
    cardHeaderBadgeTeal: {
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#A5D6A7',
        zIndex: 100,
        elevation: 5,
    },
    cardHeaderBadgeEmerald: {
        backgroundColor: '#E6F4F1',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#B2DFDB',
        zIndex: 100,
        elevation: 5,
    },
    cardHeaderBadgeCyan: {
        backgroundColor: '#E0F7FA',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 10,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#0EA5E9',
        zIndex: 100,
        elevation: 5,
    },
    cardBadgeText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: '800',
    },
    cardBadgeTextDark: {
        color: '#333',
        fontSize: 10,
        fontFamily: 'Inter_600SemiBold',
        textAlign: 'center',
    },
    cardMainContent: {
        flex: 1,
        justifyContent: 'center',
        marginTop: 10,
    },
    cardIconRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginBottom: 5,
    },
    actionCardIcon: {
        width: 40,
        height: 40,
        alignSelf: 'center',
    },
    saiLotusIcon: {
        width: 40,
        height: 40,
        alignSelf: 'center',
    },
    cardBadgeIcon: {
        marginRight: 4,
    },
    cardTypeLabel: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: '900',
    },
    cardTitleLarge: {
        color: '#FFF',
        fontSize: 13,
        fontWeight: '900',
        lineHeight: 16,
    },
    cardTitleLargeDark: {
        color: '#111111',
        fontSize: Platform.OS === 'ios' ? 12 : 10,
        fontWeight: '800',
        maxWidth: '100%',
        marginBottom: 4,
        lineHeight: Platform.OS === 'ios' ? 14 : 12,
    },
    cardSubtitleSmallDark: {
        color: '#5A5A5A',
        fontSize: Platform.OS === 'ios' ? 9.8 : 8.8,
        fontWeight: '600',
        maxWidth: '100%',
        lineHeight: Platform.OS === 'ios' ? 12 : 10.5,
    },
    cardLocationText: {
        color: '#666',
        fontSize: 10,
        fontWeight: '800',
        marginTop: 4,
    },
    cardNotifyRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
        gap: 4,
    },
    cardNotifyText: {
        color: '#5A5A5A',
        fontSize: 11,
        fontWeight: '600',
        flex: 1,
    },
    cardButtonWhite: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardButtonWhiteText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: '900',
    },
    cardButtonOutline: {
        width: Platform.OS === 'ios' ? 76 : 60,
        height: 19,
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        paddingHorizontal: 4,
    },
    cardButtonOutlineTeal: {
        width: Platform.OS === 'ios' ? 76 : 60,
        height: 19,
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        paddingHorizontal: 4,
    },
    cardButtonOutlineCyan: {
        width: Platform.OS === 'ios' ? 76 : 60,
        height: 19,
        borderRadius: 6,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        paddingHorizontal: 4,
    },
    cardButtonTextDark: {
        fontSize: 9,
        fontWeight: '800',
        color: '#000',
    },
    dots: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        marginBottom: 20,
    },
    dot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#CCC',
    },
    activeDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#FF6B00',
    },
    twoButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
        gap: 6,
        paddingHorizontal: 10,
    },
    bigServiceButton: {
        width: 174,
        height: 70,
        borderRadius: 18,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    bigButtonGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 15,
        gap: 12,
    },
    bigButtonIcon: {
        width: 32,
        height: 32,
    },
    bigButtonText: {
        fontSize: 15,
        fontWeight: '800',
        color: '#333',
        flex: 1,
    },
    communityCardMini: {
        flex: 1,
        minHeight: 75,
        paddingVertical: 10,
        backgroundColor: '#FFFFFF',
        borderRadius: 15,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
        ...(Platform.OS === 'android' ? {
            flexBasis: '48%',
            maxWidth: '49%',
            flexShrink: 1,
        } : {}),
    },
    miniCardIconBox: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#F3E5F5',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
    },
    miniCardImageBox: {
        width: 44,
        height: 44,
        borderRadius: 22,
        marginRight: 8,
        overflow: 'hidden',
    },
    miniCardCircleImg: {
        width: '100%',
        height: '100%',
    },
    communityCardIcon: {
        width: 44,
        height: 44,
        borderRadius: 10,
        marginRight: 8,
    },
    communityCardIconBox: {
        width: 44,
        height: 44,
        borderRadius: 10,
        marginRight: 8,
        overflow: 'hidden',
    },
    communityCardIconRound: {
        width: '100%',
        height: '100%',
    },
    miniCardContent: {
        flex: 1,
        justifyContent: 'center',
    },
    communityCardTextBlock: {
        marginTop: 6,
    },
    miniCardType: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 7,
        color: '#8C36DB',
        letterSpacing: 0.5,
        marginBottom: 2,
    },
    communityCardLabel: {
        color: '#9F45FF',
        fontSize: Platform.OS === 'android' ? 8.5 : 10,
        letterSpacing: 0,
        marginBottom: 2,
    },
    miniCardTitle: {
        fontFamily: 'Outfit_700Bold',
        fontSize: 10,
        color: '#111',
        lineHeight: 12,
    },
    communityCardTitle: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: Platform.OS === 'android' ? 10.5 : 12.5,
        color: '#000',
        lineHeight: Platform.OS === 'android' ? 13 : 15,
    },
    miniCardMembers: {
        fontFamily: 'Inter_500Medium',
        fontSize: 8,
        color: '#888',
        marginTop: 1,
    },
    communityCardMembers: {
        fontSize: Platform.OS === 'android' ? 8.5 : 10,
        color: '#000',
        marginTop: 2,
    },
    miniCardBottomRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 6,
    },
    sevaBadgeMini: {
        width: 30,
        height: 15,
        borderRadius: 7.5,
        borderWidth: 1,
        borderColor: '#365F35',
        backgroundColor: '#FFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sevaBadgeTextMini: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 8.5,
        color: '#397339',
    },
    stickyFeedTabsShell: {
        backgroundColor: '#FFF',
        marginTop: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 10,
        zIndex: 100,
    },
    stickyFeedTabs: {
        backgroundColor: '#FFF',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        paddingHorizontal: 10,
    },
    feedPanel: {
        backgroundColor: '#000000',
        overflow: 'hidden',
    },
    feedLoading: {
        minHeight: 130,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    feedLoadingText: {
        color: '#F3D5C6',
        fontSize: 13,
        fontWeight: '700',
    },
    emptyFeed: {
        minHeight: 120,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyFeedText: {
        color: '#F3D5C6',
        fontSize: 14,
        fontWeight: '800',
    },
    loadMoreButton: {
        height: 42,
        marginHorizontal: 14,
        marginBottom: 14,
        borderRadius: 12,
        backgroundColor: '#FFD26C',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadMoreText: {
        color: '#321B3E',
        fontSize: 14,
        fontWeight: '900',
    },
    commentOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'flex-end',
    },
    commentSheet: {
        maxHeight: '75%',
        borderTopLeftRadius: 22,
        borderTopRightRadius: 22,
        backgroundColor: '#FFF7ED',
        paddingBottom: 12,
    },
    bottomSheetHandle: {
        alignSelf: 'center',
        width: 44,
        height: 5,
        borderRadius: 3,
        backgroundColor: '#D8C8D6',
        marginTop: 10,
        marginBottom: 8,
    },
    commentSheetHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingBottom: 12,
    },
    commentTitle: {
        color: '#22142E',
        fontSize: 18,
        fontWeight: '900',
    },
    commentCloseBtn: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F0E5EA',
    },
    commentPostPreview: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 16,
        marginBottom: 10,
        padding: 10,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
    },
    commentPreviewTextWrap: {
        flex: 1,
        marginLeft: 10,
    },
    commentPreviewUser: {
        color: '#22142E',
        fontSize: 13,
        fontWeight: '900',
    },
    commentPreviewCaption: {
        color: '#5B4A55',
        fontSize: 12,
        marginTop: 2,
    },
    commentListWrap: {
        minHeight: 200,
        maxHeight: 360,
        paddingHorizontal: 16,
    },
    commentItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    commentBubble: {
        flex: 1,
        marginLeft: 10,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
        padding: 10,
    },
    inlineDeletePopover: {
        position: 'absolute',
        right: 0,
        top: 20,
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 5,
        minWidth: 80,
        zIndex: 999,
    },
    inlineDeleteText: {
        color: '#FF3B30',
        fontSize: 13,
        fontWeight: '600',
        marginLeft: 6,
    },
    commentItemUser: {
        color: '#22142E',
        fontSize: 13,
        fontWeight: '900',
    },
    commentItemText: {
        color: '#3A2C36',
        fontSize: 13,
        lineHeight: 18,
        marginTop: 3,
    },
    commentTime: {
        color: '#8A7B89',
        fontSize: 11,
        marginTop: 5,
    },
    commentEmptyState: {
        minHeight: 180,
        alignItems: 'center',
        justifyContent: 'center',
    },
    commentEmptyText: {
        color: '#5B4A55',
        fontSize: 14,
        fontWeight: '800',
        textAlign: 'center',
    },
    commentEmptySubtext: {
        color: '#8A7B89',
        fontSize: 12,
        marginTop: 4,
    },
    commentInputWrap: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 8,
        paddingHorizontal: 16,
        paddingTop: 10,
    },
    commentInput: {
        flex: 1,
        minHeight: 42,
        maxHeight: 96,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5CDBB',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 12,
        paddingVertical: 10,
        color: '#22142E',
        fontSize: 14,
    },
    commentSubmitBtn: {
        width: 42,
        height: 42,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F0E5EA',
    },
    commentSubmitDisabled: {
        opacity: 0.7,
    },
    postCard: {
        padding: 14,
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    postAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FFB36D',
        borderWidth: 2,
        borderColor: '#FFE4B2',
        alignItems: 'center',
        justifyContent: 'center',
    },
    postAvatarText: {
        color: '#3A182E',
        fontSize: 20,
        fontWeight: '900',
    },
    postAuthor: {
        flex: 1,
        marginLeft: 10,
    },
    postName: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '900',
    },
    postMeta: {
        color: '#F1D6C8',
        fontSize: 12,
        fontWeight: '700',
        marginTop: 2,
    },
    postTime: {
        color: '#EFD8C9',
        fontSize: 12,
        fontWeight: '700',
        marginRight: 10,
    },
    postText: {
        color: '#FFFFFF',
        fontSize: 15,
        lineHeight: 21,
        fontWeight: '700',
        marginTop: 12,
        marginBottom: 12,
    },
    postImage: {
        height: 158,
        borderRadius: 12,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    postImageRadius: {
        borderRadius: 12,
    },
    bigPlay: {
        width: 62,
        height: 62,
        borderRadius: 31,
        borderWidth: 2,
        borderColor: '#FFFFFF',
        backgroundColor: 'rgba(0,0,0,0.42)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    videoTime: {
        position: 'absolute',
        right: 9,
        bottom: 8,
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '900',
    },
    actionRow: {
        height: 38,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 22,
    },
    actionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    actionText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '800',
    },
    bookmark: {
        marginLeft: 'auto',
    },
    uploadingStatusBar: {
        position: 'absolute',
        bottom: 90,
        left: 16,
        right: 16,
        backgroundColor: 'rgba(30, 30, 30, 0.95)',
        borderRadius: 12,
        padding: 12,
        zIndex: 9999,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 24,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    uploadingStatusContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    uploadingThumbnail: {
        width: 40,
        height: 40,
        borderRadius: 6,
        marginRight: 12,
        backgroundColor: '#333',
    },
    uploadingTextContainer: {
        flex: 1,
    },
    uploadingTitle: {
        color: '#FFF',
        fontSize: 13,
        fontWeight: '800',
        marginBottom: 8,
    },
    progressBarBg: {
        height: 3,
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
    },
    // Search Styles
    searchPanel: {
        backgroundColor: '#FFF',
        marginHorizontal: PAGE_PADDING,
        marginTop: -10,
        marginBottom: 20,
        borderRadius: 16,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 44,
    },
    searchInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 15,
        color: '#333',
        fontWeight: '600',
    },
    searchResultsSection: {
        marginTop: 15,
    },
    userResultItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    userResultContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    userResultText: {
        marginLeft: 12,
        flex: 1,
    },
    userResultName: {
        fontSize: 15,
        fontWeight: '800',
        color: '#111',
    },
    userResultMeta: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    followButton: {
        backgroundColor: '#FF6B00',
        paddingHorizontal: 15,
        paddingVertical: 6,
        borderRadius: 20,
    },
    followingButton: {
        backgroundColor: '#F0F0F0',
    },
    followButtonText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: '800',
    },
    followingButtonText: {
        color: '#666',
    },
    searchStatusText: {
        textAlign: 'center',
        color: '#666',
        fontSize: 14,
        marginVertical: 10,
    },
    hashtagIcon: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: '#F3E5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    recentSearchesTitle: {
        fontSize: 14,
        fontFamily: FONTS.bold,
        color: '#6F5C70',
        marginBottom: 0,
    },
    recentSearchSection: {
        marginTop: 15,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    recentSearchHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    clearHistoryText: {
        fontSize: 12,
        fontFamily: FONTS.bold,
        color: '#888', // Subtle color for history clear
        textDecorationLine: 'underline',
    },
    recentSearchList: {
        paddingRight: 20,
        gap: 20,
    },
    recentSearchItem: {
        alignItems: 'center',
        width: 70,
    },
    recentSearchName: {
        fontSize: 11,
        fontFamily: FONTS.bold,
        color: '#333',
        marginTop: 6,
        textAlign: 'center',
    },
    // Bio Modal Styles
    bioModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    bioModalCard: {
        width: '100%',
        backgroundColor: '#FFF',
        borderRadius: 20,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 20,
        elevation: 10,
    },
    bioModalTitle: {
        fontSize: 20,
        fontWeight: '900',
        color: '#1C1B1F',
        marginBottom: 16,
    },
    bioModalInput: {
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        color: '#333',
        minHeight: 100,
        textAlignVertical: 'top',
        marginBottom: 20,
    },
    bioModalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
    },
    bioModalBtn: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        backgroundColor: '#FF6B00',
    },
    bioModalBtnCancel: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 12,
        backgroundColor: '#F5F5F5',
    },
    bioModalBtnText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '800',
    },
    bioModalBtnCancelText: {
        color: '#666',
        fontSize: 16,
        fontWeight: '800',
    },
    modalBackgroundDismiss: {
        ...StyleSheet.absoluteFillObject,
    },
    commentThreadLine: {
        position: 'absolute',
        left: 15,
        top: 32,
        bottom: 0,
        width: 1.5,
        backgroundColor: '#E6E1E8',
        zIndex: 1,
    },
    replyItemContainer: {
        marginLeft: 42,
        marginTop: 8,
        position: 'relative',
    },
    replyThreadVerticalLine: {
        position: 'absolute',
        left: -26,
        top: 0,
        bottom: 0,
        width: 1.5,
        backgroundColor: '#E6E1E8',
        zIndex: 1,
    },
    replyThreadVerticalLineLast: {
        position: 'absolute',
        left: -26,
        top: 0,
        height: 12,
        width: 1.5,
        backgroundColor: '#E6E1E8',
        zIndex: 1,
    },
    replyThreadHorizontalLine: {
        position: 'absolute',
        left: -26,
        top: 12,
        width: 26,
        height: 1.5,
        backgroundColor: '#E6E1E8',
        zIndex: 1,
    },
    replyCommentBubble: {
        backgroundColor: '#F8F5F9',
    },
    commentActionButton: {
        padding: 4,
        marginRight: -4,
        marginTop: -4,
    },
});
