const ALL_SHAKTI_DATA = {
  'shaktipeeth-renuka-devi-temple-mahur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-renuka-devi-temple-mahur-sp1',
        name: 'Renuka Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Renuka Devi Temple.',
        locationQuery: 'Renuka Devi Temple Sacred Kund Mahur',
      },
      {
        id: 'shaktipeeth-renuka-devi-temple-mahur-sp2',
        name: 'Renuka Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Renuka Devi Temple Temple Mahur',
      },
      {
        id: 'shaktipeeth-renuka-devi-temple-mahur-sp3',
        name: 'Renuka Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Mahur.',
        locationQuery: 'Renuka Devi Temple Viewpoint Mahur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-bakreshwar-temple-birbhum': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-bakreshwar-temple-birbhum-sp1',
        name: 'Bakreshwar Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Bakreshwar Temple.',
        locationQuery: 'Bakreshwar Temple Sacred Kund Suri',
      },
      {
        id: 'shaktipeeth-bakreshwar-temple-birbhum-sp2',
        name: 'Bakreshwar Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Bakreshwar Temple Temple Suri',
      },
      {
        id: 'shaktipeeth-bakreshwar-temple-birbhum-sp3',
        name: 'Bakreshwar Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Suri.',
        locationQuery: 'Bakreshwar Temple Viewpoint Suri',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-vaishno-devi-temple-jammu-kashmir': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-vaishno-devi-temple-jammu-kashmir-sp1',
        name: 'Vaishno Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Vaishno Devi Temple.',
        locationQuery: 'Vaishno Devi Temple Sacred Kund Katra',
      },
      {
        id: 'shaktipeeth-vaishno-devi-temple-jammu-kashmir-sp2',
        name: 'Vaishno Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Vaishno Devi Temple Temple Katra',
      },
      {
        id: 'shaktipeeth-vaishno-devi-temple-jammu-kashmir-sp3',
        name: 'Vaishno Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Katra.',
        locationQuery: 'Vaishno Devi Temple Viewpoint Katra',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-hinglaj-devi-rajasthan': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-hinglaj-devi-rajasthan-sp1',
        name: 'Hinglaj Mata Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Hinglaj Mata Temple.',
        locationQuery: 'Hinglaj Mata Temple Sacred Kund Barmer',
      },
      {
        id: 'shaktipeeth-hinglaj-devi-rajasthan-sp2',
        name: 'Hinglaj Mata Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Hinglaj Mata Temple Temple Barmer',
      },
      {
        id: 'shaktipeeth-hinglaj-devi-rajasthan-sp3',
        name: 'Hinglaj Mata Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Barmer.',
        locationQuery: 'Hinglaj Mata Temple Viewpoint Barmer',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'sacred-mahakali-temple-pavagadh': {
    sacredPlaces: [
      {
        id: 'sacred-mahakali-temple-pavagadh-sp1',
        name: 'Kalika Mata Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Kalika Mata Temple.',
        locationQuery: 'Kalika Mata Temple Sacred Kund Panchmahal',
      },
      {
        id: 'sacred-mahakali-temple-pavagadh-sp2',
        name: 'Kalika Mata Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Kalika Mata Temple Temple Panchmahal',
      },
      {
        id: 'sacred-mahakali-temple-pavagadh-sp3',
        name: 'Kalika Mata Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Panchmahal.',
        locationQuery: 'Kalika Mata Temple Viewpoint Panchmahal',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-tarapith-temple-birbhum': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-tarapith-temple-birbhum-sp1',
        name: 'Tarapith Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Tarapith Temple.',
        locationQuery: 'Tarapith Temple Sacred Kund Tarapith',
      },
      {
        id: 'shaktipeeth-tarapith-temple-birbhum-sp2',
        name: 'Tarapith Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Tarapith Temple Temple Tarapith',
      },
      {
        id: 'shaktipeeth-tarapith-temple-birbhum-sp3',
        name: 'Tarapith Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Tarapith.',
        locationQuery: 'Tarapith Temple Viewpoint Tarapith',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-sharda-peeth-kashmir': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-sharda-peeth-kashmir-sp1',
        name: 'Sharada Peeth Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Sharada Peeth.',
        locationQuery: 'Sharada Peeth Sacred Kund Kupwara',
      },
      {
        id: 'shaktipeeth-sharda-peeth-kashmir-sp2',
        name: 'Sharada Peeth Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Sharada Peeth Temple Kupwara',
      },
      {
        id: 'shaktipeeth-sharda-peeth-kashmir-sp3',
        name: 'Sharada Peeth Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kupwara.',
        locationQuery: 'Sharada Peeth Viewpoint Kupwara',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-tripora-sundari-temple-tripura': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-tripora-sundari-temple-tripura-sp1',
        name: 'Tripura Sundari Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Tripura Sundari Temple.',
        locationQuery: 'Tripura Sundari Temple Sacred Kund Udaipur',
      },
      {
        id: 'shaktipeeth-tripora-sundari-temple-tripura-sp2',
        name: 'Tripura Sundari Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Tripura Sundari Temple Temple Udaipur',
      },
      {
        id: 'shaktipeeth-tripora-sundari-temple-tripura-sp3',
        name: 'Tripura Sundari Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Udaipur.',
        locationQuery: 'Tripura Sundari Temple Viewpoint Udaipur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-saptashrungi-temple-nashik': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-saptashrungi-temple-nashik-sp1',
        name: 'Saptashrungi Nivasini Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Saptashrungi Nivasini Temple.',
        locationQuery: 'Saptashrungi Nivasini Temple Sacred Kund Vani',
      },
      {
        id: 'shaktipeeth-saptashrungi-temple-nashik-sp2',
        name: 'Saptashrungi Nivasini Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Saptashrungi Nivasini Temple Temple Vani',
      },
      {
        id: 'shaktipeeth-saptashrungi-temple-nashik-sp3',
        name: 'Saptashrungi Nivasini Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Vani.',
        locationQuery: 'Saptashrungi Nivasini Temple Viewpoint Vani',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-devi-patan-temple-balrampur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-devi-patan-temple-balrampur-sp1',
        name: 'Devi Patan Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Devi Patan Temple.',
        locationQuery: 'Devi Patan Temple Sacred Kund Balrampur',
      },
      {
        id: 'shaktipeeth-devi-patan-temple-balrampur-sp2',
        name: 'Devi Patan Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Devi Patan Temple Temple Balrampur',
      },
      {
        id: 'shaktipeeth-devi-patan-temple-balrampur-sp3',
        name: 'Devi Patan Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Balrampur.',
        locationQuery: 'Devi Patan Temple Viewpoint Balrampur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-chintpurni-devi-temple-una': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-chintpurni-devi-temple-una-sp1',
        name: 'Chintpurni Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Chintpurni Devi Temple.',
        locationQuery: 'Chintpurni Devi Temple Sacred Kund Una',
      },
      {
        id: 'shaktipeeth-chintpurni-devi-temple-una-sp2',
        name: 'Chintpurni Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Chintpurni Devi Temple Temple Una',
      },
      {
        id: 'shaktipeeth-chintpurni-devi-temple-una-sp3',
        name: 'Chintpurni Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Una.',
        locationQuery: 'Chintpurni Devi Temple Viewpoint Una',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-jwala-ji-temple-kangra': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-jwala-ji-temple-kangra-sp1',
        name: 'Jwala Ji Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Jwala Ji Temple.',
        locationQuery: 'Jwala Ji Temple Sacred Kund Kangra',
      },
      {
        id: 'shaktipeeth-jwala-ji-temple-kangra-sp2',
        name: 'Jwala Ji Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Jwala Ji Temple Temple Kangra',
      },
      {
        id: 'shaktipeeth-jwala-ji-temple-kangra-sp3',
        name: 'Jwala Ji Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kangra.',
        locationQuery: 'Jwala Ji Temple Viewpoint Kangra',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-bhavani-mandir-tuljapur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-bhavani-mandir-tuljapur-sp1',
        name: 'Tulja Bhavani Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Tulja Bhavani Temple.',
        locationQuery: 'Tulja Bhavani Temple Sacred Kund Tuljapur',
      },
      {
        id: 'shaktipeeth-bhavani-mandir-tuljapur-sp2',
        name: 'Tulja Bhavani Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Tulja Bhavani Temple Temple Tuljapur',
      },
      {
        id: 'shaktipeeth-bhavani-mandir-tuljapur-sp3',
        name: 'Tulja Bhavani Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Tuljapur.',
        locationQuery: 'Tulja Bhavani Temple Viewpoint Tuljapur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-kalighat-kali-temple-kolkata': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-kalighat-kali-temple-kolkata-sp1',
        name: 'Kalighat Kali Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Kalighat Kali Temple.',
        locationQuery: 'Kalighat Kali Temple Sacred Kund Kolkata',
      },
      {
        id: 'shaktipeeth-kalighat-kali-temple-kolkata-sp2',
        name: 'Kalighat Kali Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Kalighat Kali Temple Temple Kolkata',
      },
      {
        id: 'shaktipeeth-kalighat-kali-temple-kolkata-sp3',
        name: 'Kalighat Kali Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kolkata.',
        locationQuery: 'Kalighat Kali Temple Viewpoint Kolkata',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-harsiddhi-mata-temple-ujjain': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-harsiddhi-mata-temple-ujjain-sp1',
        name: 'Harsiddhi Mata Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Harsiddhi Mata Temple.',
        locationQuery: 'Harsiddhi Mata Temple Sacred Kund Ujjain',
      },
      {
        id: 'shaktipeeth-harsiddhi-mata-temple-ujjain-sp2',
        name: 'Harsiddhi Mata Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Harsiddhi Mata Temple Temple Ujjain',
      },
      {
        id: 'shaktipeeth-harsiddhi-mata-temple-ujjain-sp3',
        name: 'Harsiddhi Mata Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Ujjain.',
        locationQuery: 'Harsiddhi Mata Temple Viewpoint Ujjain',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-biraja-temple-jajpur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-biraja-temple-jajpur-sp1',
        name: 'Biraja Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Biraja Temple.',
        locationQuery: 'Biraja Temple Sacred Kund Jajpur',
      },
      {
        id: 'shaktipeeth-biraja-temple-jajpur-sp2',
        name: 'Biraja Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Biraja Temple Temple Jajpur',
      },
      {
        id: 'shaktipeeth-biraja-temple-jajpur-sp3',
        name: 'Biraja Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Jajpur.',
        locationQuery: 'Biraja Temple Viewpoint Jajpur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-mahalaxmi-temple-kolhapur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-mahalaxmi-temple-kolhapur-sp1',
        name: 'Mahalaxmi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Mahalaxmi Temple.',
        locationQuery: 'Mahalaxmi Temple Sacred Kund Kolhapur',
      },
      {
        id: 'shaktipeeth-mahalaxmi-temple-kolhapur-sp2',
        name: 'Mahalaxmi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Mahalaxmi Temple Temple Kolhapur',
      },
      {
        id: 'shaktipeeth-mahalaxmi-temple-kolhapur-sp3',
        name: 'Mahalaxmi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kolhapur.',
        locationQuery: 'Mahalaxmi Temple Viewpoint Kolhapur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-sharada-devi-temple-maihar': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-sharada-devi-temple-maihar-sp1',
        name: 'Sharada Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Sharada Devi Temple.',
        locationQuery: 'Sharada Devi Temple Sacred Kund Maihar',
      },
      {
        id: 'shaktipeeth-sharada-devi-temple-maihar-sp2',
        name: 'Sharada Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Sharada Devi Temple Temple Maihar',
      },
      {
        id: 'shaktipeeth-sharada-devi-temple-maihar-sp3',
        name: 'Sharada Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Maihar.',
        locationQuery: 'Sharada Devi Temple Viewpoint Maihar',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-naina-devi-temple-bilaspur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-naina-devi-temple-bilaspur-sp1',
        name: 'Naina Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Naina Devi Temple.',
        locationQuery: 'Naina Devi Temple Sacred Kund Bilaspur',
      },
      {
        id: 'shaktipeeth-naina-devi-temple-bilaspur-sp2',
        name: 'Naina Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Naina Devi Temple Temple Bilaspur',
      },
      {
        id: 'shaktipeeth-naina-devi-temple-bilaspur-sp3',
        name: 'Naina Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Bilaspur.',
        locationQuery: 'Naina Devi Temple Viewpoint Bilaspur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-kamakhya-temple-guwahati': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-kamakhya-temple-guwahati-sp1',
        name: 'Kamakhya Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Kamakhya Temple.',
        locationQuery: 'Kamakhya Temple Sacred Kund Guwahati',
      },
      {
        id: 'shaktipeeth-kamakhya-temple-guwahati-sp2',
        name: 'Kamakhya Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Kamakhya Temple Temple Guwahati',
      },
      {
        id: 'shaktipeeth-kamakhya-temple-guwahati-sp3',
        name: 'Kamakhya Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Guwahati.',
        locationQuery: 'Kamakhya Temple Viewpoint Guwahati',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-vindhyavasini-temple-vindhyachal': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-vindhyavasini-temple-vindhyachal-sp1',
        name: 'Vindhyavasini Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Vindhyavasini Temple.',
        locationQuery: 'Vindhyavasini Temple Sacred Kund Mirzapur',
      },
      {
        id: 'shaktipeeth-vindhyavasini-temple-vindhyachal-sp2',
        name: 'Vindhyavasini Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Vindhyavasini Temple Temple Mirzapur',
      },
      {
        id: 'shaktipeeth-vindhyavasini-temple-vindhyachal-sp3',
        name: 'Vindhyavasini Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Mirzapur.',
        locationQuery: 'Vindhyavasini Temple Viewpoint Mirzapur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-chinnamasta-temple-rajarappa': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-chinnamasta-temple-rajarappa-sp1',
        name: 'Chinnamasta Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Chinnamasta Temple.',
        locationQuery: 'Chinnamasta Temple Sacred Kund Ramgarh',
      },
      {
        id: 'shaktipeeth-chinnamasta-temple-rajarappa-sp2',
        name: 'Chinnamasta Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Chinnamasta Temple Temple Ramgarh',
      },
      {
        id: 'shaktipeeth-chinnamasta-temple-rajarappa-sp3',
        name: 'Chinnamasta Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Ramgarh.',
        locationQuery: 'Chinnamasta Temple Viewpoint Ramgarh',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-kamakhya-kanya-kumari-temple': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-kamakhya-kanya-kumari-temple-sp1',
        name: 'Kanyakumari Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Kanyakumari Devi Temple.',
        locationQuery: 'Kanyakumari Devi Temple Sacred Kund Kanyakumari',
      },
      {
        id: 'shaktipeeth-kamakhya-kanya-kumari-temple-sp2',
        name: 'Kanyakumari Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Kanyakumari Devi Temple Temple Kanyakumari',
      },
      {
        id: 'shaktipeeth-kamakhya-kanya-kumari-temple-sp3',
        name: 'Kanyakumari Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kanyakumari.',
        locationQuery: 'Kanyakumari Devi Temple Viewpoint Kanyakumari',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-jogadya-temple-burdwan': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-jogadya-temple-burdwan-sp1',
        name: 'Jogadya Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Jogadya Temple.',
        locationQuery: 'Jogadya Temple Sacred Kund Burdwan',
      },
      {
        id: 'shaktipeeth-jogadya-temple-burdwan-sp2',
        name: 'Jogadya Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Jogadya Temple Temple Burdwan',
      },
      {
        id: 'shaktipeeth-jogadya-temple-burdwan-sp3',
        name: 'Jogadya Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Burdwan.',
        locationQuery: 'Jogadya Temple Viewpoint Burdwan',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-chamunda-devi-temple-kangra': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-chamunda-devi-temple-kangra-sp1',
        name: 'Chamunda Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Chamunda Devi Temple.',
        locationQuery: 'Chamunda Devi Temple Sacred Kund Kangra',
      },
      {
        id: 'shaktipeeth-chamunda-devi-temple-kangra-sp2',
        name: 'Chamunda Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Chamunda Devi Temple Temple Kangra',
      },
      {
        id: 'shaktipeeth-chamunda-devi-temple-kangra-sp3',
        name: 'Chamunda Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kangra.',
        locationQuery: 'Chamunda Devi Temple Viewpoint Kangra',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-tara-tarini-temple-ganjam': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-tara-tarini-temple-ganjam-sp1',
        name: 'Tara Tarini Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Tara Tarini Temple.',
        locationQuery: 'Tara Tarini Temple Sacred Kund Berhampur',
      },
      {
        id: 'shaktipeeth-tara-tarini-temple-ganjam-sp2',
        name: 'Tara Tarini Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Tara Tarini Temple Temple Berhampur',
      },
      {
        id: 'shaktipeeth-tara-tarini-temple-ganjam-sp3',
        name: 'Tara Tarini Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Berhampur.',
        locationQuery: 'Tara Tarini Temple Viewpoint Berhampur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-danteshwari-temple-dantewada': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-danteshwari-temple-dantewada-sp1',
        name: 'Danteshwari Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Danteshwari Temple.',
        locationQuery: 'Danteshwari Temple Sacred Kund Dantewada',
      },
      {
        id: 'shaktipeeth-danteshwari-temple-dantewada-sp2',
        name: 'Danteshwari Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Danteshwari Temple Temple Dantewada',
      },
      {
        id: 'shaktipeeth-danteshwari-temple-dantewada-sp3',
        name: 'Danteshwari Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Dantewada.',
        locationQuery: 'Danteshwari Temple Viewpoint Dantewada',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-brareshwari-devi-temple-kangra': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-brareshwari-devi-temple-kangra-sp1',
        name: 'Brajeshwari Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Brajeshwari Devi Temple.',
        locationQuery: 'Brajeshwari Devi Temple Sacred Kund Kangra',
      },
      {
        id: 'shaktipeeth-brareshwari-devi-temple-kangra-sp2',
        name: 'Brajeshwari Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Brajeshwari Devi Temple Temple Kangra',
      },
      {
        id: 'shaktipeeth-brareshwari-devi-temple-kangra-sp3',
        name: 'Brajeshwari Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Kangra.',
        locationQuery: 'Brajeshwari Devi Temple Viewpoint Kangra',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-chamundeshwari-temple-mysore': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-chamundeshwari-temple-mysore-sp1',
        name: 'Chamundeshwari Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Chamundeshwari Temple.',
        locationQuery: 'Chamundeshwari Temple Sacred Kund Mysuru',
      },
      {
        id: 'shaktipeeth-chamundeshwari-temple-mysore-sp2',
        name: 'Chamundeshwari Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Chamundeshwari Temple Temple Mysuru',
      },
      {
        id: 'shaktipeeth-chamundeshwari-temple-mysore-sp3',
        name: 'Chamundeshwari Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Mysuru.',
        locationQuery: 'Chamundeshwari Temple Viewpoint Mysuru',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-alopi-devi-temple-prayagraj': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-alopi-devi-temple-prayagraj-sp1',
        name: 'Alopi Devi Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Alopi Devi Temple.',
        locationQuery: 'Alopi Devi Temple Sacred Kund Prayagraj',
      },
      {
        id: 'shaktipeeth-alopi-devi-temple-prayagraj-sp2',
        name: 'Alopi Devi Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Alopi Devi Temple Temple Prayagraj',
      },
      {
        id: 'shaktipeeth-alopi-devi-temple-prayagraj-sp3',
        name: 'Alopi Devi Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Prayagraj.',
        locationQuery: 'Alopi Devi Temple Viewpoint Prayagraj',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-ambaji-temple-gujarat': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-ambaji-temple-gujarat-sp1',
        name: 'Ambaji Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Ambaji Temple.',
        locationQuery: 'Ambaji Temple Sacred Kund Ambaji',
      },
      {
        id: 'shaktipeeth-ambaji-temple-gujarat-sp2',
        name: 'Ambaji Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Ambaji Temple Temple Ambaji',
      },
      {
        id: 'shaktipeeth-ambaji-temple-gujarat-sp3',
        name: 'Ambaji Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Ambaji.',
        locationQuery: 'Ambaji Temple Viewpoint Ambaji',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-nalateswari-temple-nalhati': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-nalateswari-temple-nalhati-sp1',
        name: 'Nalateswari Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Nalateswari Temple.',
        locationQuery: 'Nalateswari Temple Sacred Kund Nalhati',
      },
      {
        id: 'shaktipeeth-nalateswari-temple-nalhati-sp2',
        name: 'Nalateswari Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Nalateswari Temple Temple Nalhati',
      },
      {
        id: 'shaktipeeth-nalateswari-temple-nalhati-sp3',
        name: 'Nalateswari Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Nalhati.',
        locationQuery: 'Nalateswari Temple Viewpoint Nalhati',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-attahas-temple-birbhum': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-attahas-temple-birbhum-sp1',
        name: 'Fullara Attahas Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Fullara Attahas Temple.',
        locationQuery: 'Fullara Attahas Temple Sacred Kund Labhpur',
      },
      {
        id: 'shaktipeeth-attahas-temple-birbhum-sp2',
        name: 'Fullara Attahas Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Fullara Attahas Temple Temple Labhpur',
      },
      {
        id: 'shaktipeeth-attahas-temple-birbhum-sp3',
        name: 'Fullara Attahas Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Labhpur.',
        locationQuery: 'Fullara Attahas Temple Viewpoint Labhpur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
  'shaktipeeth-kankalitala-temple-bolpur': {
    sacredPlaces: [
      {
        id: 'shaktipeeth-kankalitala-temple-bolpur-sp1',
        name: 'Kankalitala Temple Sacred Kund & Tank',
        category: 'Ghat',
        distance: '0.5 km',
        significance: 'Sacred water body used for ritual purifications before entering Kankalitala Temple.',
        locationQuery: 'Kankalitala Temple Sacred Kund Bolpur',
      },
      {
        id: 'shaktipeeth-kankalitala-temple-bolpur-sp2',
        name: 'Kankalitala Temple Sanctum & Parikrama Marg',
        category: 'Heritage',
        distance: '0.2 km',
        significance: 'Sacred circumambulation path surrounded by ancient divine energy.',
        locationQuery: 'Kankalitala Temple Temple Bolpur',
      },
      {
        id: 'shaktipeeth-kankalitala-temple-bolpur-sp3',
        name: 'Kankalitala Temple Viewpoint & Hill Ridge',
        category: 'Heritage',
        distance: '1.2 km',
        significance: 'Panoramic view of the sacred pilgrimage town of Bolpur.',
        locationQuery: 'Kankalitala Temple Viewpoint Bolpur',
      },
    ],
    nearbyTemples: [
      {
        templeId: 'shaktipeeth-kamakhya-temple-guwahati',
        name: 'Kamakhya Temple Guwahati',
        image: getTempleImageById('shaktipeeth-kamakhya-temple-guwahati'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-kalighat-kali-temple-kolkata',
        name: 'Kalighat Kali Temple Kolkata',
        image: getTempleImageById('shaktipeeth-kalighat-kali-temple-kolkata'),
        distance: 'Sacred Circuit',
      },
      {
        templeId: 'shaktipeeth-ambaji-temple-gujarat',
        name: 'Ambaji Temple Gujarat',
        image: getTempleImageById('shaktipeeth-ambaji-temple-gujarat'),
        distance: 'Sacred Circuit',
      },
    ],
  },
};
