export const FESTIVAL_IMAGE_MAP: Record<string, any> = {
  'Akshaya Tritiya': require('../../assets/images/festivals/Akshaya Tritiya.jpg'),
  'Anant Chaturdashi': require('../../assets/images/festivals/Anant Chaturdashi.jpg'),
  'Ashadhi Ekadashi': require('../../assets/images/festivals/Ashadhi Ekadashi_.jpg'),
  'Bhai Dooj': require('../../assets/images/festivals/Bhai Dooj.jpg'),
  'Bohag Bihu': require('../../assets/images/festivals/Bohag Bihu.jpg'),
  'Chaitra Sukhladi': require('../../assets/images/festivals/Chaitra Sukhladi.jpg'),
  'Chhath Puja': require('../../assets/images/festivals/Chhath Puja.jpg'),
  'Dhanteras': require('../../assets/images/festivals/Dhanteras.jpg'),
  'Dhanu Sankranti': require('../../assets/images/festivals/Dhanu Sankranti.jpeg'),
  'Diwali': require('../../assets/images/festivals/Diwali.jpeg'),
  'Durga Ashtami': require('../../assets/images/festivals/Durga Ashtami.jpeg'),
  'Dussehra': require('../../assets/images/festivals/Dussehra.jpg'),
  'Ganesh Chaturthi': require('../../assets/images/festivals/Ganesh Chaturthi.jpeg'),
  'Geeta Jayanti': require('../../assets/images/festivals/Geeta Jayanti.jpg'),
  'Govardhan Puja': require('../../assets/images/festivals/Govardhan Puja.jpg'),
  'Guru Purnima': require('../../assets/images/festivals/Guru Purnima.jpg'),
  'Hanuman janmotsav': require('../../assets/images/festivals/Hanuman janmotsav.jpg'),
  'Holi': require('../../assets/images/festivals/Happy Holi.jpg'),
  'Hariyali Teej': require('../../assets/images/festivals/Hariyali Teej.jpeg'),
  'Hindi New Year': require('../../assets/images/festivals/Hindi New Year.jpg'),
  'Holika Dahan': require('../../assets/images/festivals/Holika Dahan.jpg'),
  'Jagannath Rath Yatra': require('../../assets/images/festivals/Jagannath Rath Yatra.jpg'),
  'Janmashtami': require('../../assets/images/festivals/Janmashtami.jpg'),
  'Kajari Teej': require('../../assets/images/festivals/Kajari Teej.jpeg'),
  'Kartik Purnima': require('../../assets/images/festivals/Kartik Purnima.jpeg'),
  'Karva Chauth': require('../../assets/images/festivals/Karva Chauth.jpg'),
  'Magh Bihu': require('../../assets/images/festivals/Magh Bihu.jpg'),
  'Maha Navami': require('../../assets/images/festivals/Maha Navami.jpeg'),
  'Maha Saptami': require('../../assets/images/festivals/Maha Saptami.jpg'),
  'Maha Shivaratri': require('../../assets/images/festivals/Maha Shivaratri.jpeg'),
  'Mahalaya Amavasya': require('../../assets/images/festivals/Mahalaya Amavasya.jpg'),
  'Maharishi Valmiki Jayanti': require('../../assets/images/festivals/Maharishi Valmiki Jayanti.jpg'),
  // 'Makar Sankranti': require('../../assets/images/festivals/Makar Sankranti.jpg.webp.jpeg'),
  'Nag Panchami': require('../../assets/images/festivals/Nag Panchami.jpg'),
  'Onam': require('../../assets/images/festivals/Onam.jpg'),
  'Raksha Bandhan': require('../../assets/images/festivals/Raksha Bandhan.jpg'),
  'Ram Navami': require('../../assets/images/festivals/Ram Navami.jpg'),
  'Savitri Pooja': require('../../assets/images/festivals/Savitri Pooja_.jpg'),
  'Sharad Navratri': require('../../assets/images/festivals/Sharad Navratri.jpg'),
  'Sharad Purnima': require('../../assets/images/festivals/Sharad Purnima.jpg'),
  'Thaipusam': require('../../assets/images/festivals/Thaipusam.jpg'),
  'Vaisakhi': require('../../assets/images/festivals/Vaisakhi.jpg'),
  'Vasant Panchami': require('../../assets/images/festivals/Vasant Panchami.jpg'),
  'Vishwakarma Puja': require('../../assets/images/festivals/Vishwakarma Puja.jpeg'),
};

export const getFestivalImage = (name: string) => {
  if (!name) return null;
  if (FESTIVAL_IMAGE_MAP[name]) return FESTIVAL_IMAGE_MAP[name];
  const key = Object.keys(FESTIVAL_IMAGE_MAP).find(k => name.includes(k) || k.includes(name));
  return key ? FESTIVAL_IMAGE_MAP[key] : null;
};
