export const FESTIVAL_IMAGE_MAP: Record<string, any> = {
  'Akshaya Tritiya': require('../../assets/images/Bhagvad-geeta.jpg'),
  'Anant Chaturdashi': require('../../assets/images/bhagavad_gita_3d_new.png'),
  'Ashadhi Ekadashi': require('../../assets/images/upcoming_radha_rani.png'),
  'Bhai Dooj': require('../../assets/images/upcoming_radha_rani.png'),
  'Bohag Bihu': require('../../assets/images/upcoming_radha_rani.png'),
  'Chaitra Sukhladi': require('../../assets/images/upcoming_radha_rani.png'),
  'Chhath Puja': require('../../assets/images/upcoming_ganga.jpg'),
  'Dhanteras': require('../../assets/images/upcoming_radha_rani.png'),
  'Dhanu Sankranti': require('../../assets/images/upcoming_shani.jpg'),
  'Diwali': require('../../assets/images/upcoming_radha_rani.png'),
  'Durga Ashtami': require('../../assets/images/upcoming_durga.png'),
  'Dussehra': require('../../assets/images/upcoming_durga.png'),
  'Ganesh Chaturthi': require('../../assets/images/upcoming_ganesh.jpg'),
  'Geeta Jayanti': require('../../assets/images/Bhagvad-geeta.jpg'),
  'Govardhan Puja': require('../../assets/images/upcoming_radha_rani.png'),
  'Guru Purnima': require('../../assets/images/upcoming_radha_rani.png'),
  'Hanuman janmotsav': require('../../assets/images/upcoming_radha_rani.png'),
  'Holi': require('../../assets/images/upcoming_radha_rani.png'),
  'Hariyali Teej': require('../../assets/images/upcoming_durga.png'),
  'Hindi New Year': require('../../assets/images/upcoming_radha_rani.png'),
  'Holika Dahan': require('../../assets/images/upcoming_radha_rani.png'),
  'Jagannath Rath Yatra': require('../../assets/images/upcoming_radha_rani.png'),
  'Janmashtami': require('../../assets/images/upcoming_radha_rani.png'),
  'Kajari Teej': require('../../assets/images/upcoming_durga.png'),
  'Kartik Purnima': require('../../assets/images/upcoming_radha_rani.png'),
  'Karva Chauth': require('../../assets/images/upcoming_radha_rani.png'),
  'Magh Bihu': require('../../assets/images/upcoming_radha_rani.png'),
  'Maha Navami': require('../../assets/images/upcoming_durga.png'),
  'Maha Saptami': require('../../assets/images/upcoming_durga.png'),
  'Maha Shivaratri': require('../../assets/images/upcoming_shiva.jpg'),
  'Mahalaya Amavasya': require('../../assets/images/upcoming_shiva.jpg'),
  'Maharishi Valmiki Jayanti': require('../../assets/images/Ramcharitmanas.jpg'),
  'Nag Panchami': require('../../assets/images/upcoming_shiva.jpg'),
  'Onam': require('../../assets/images/upcoming_radha_rani.png'),
  'Raksha Bandhan': require('../../assets/images/upcoming_radha_rani.png'),
  'Ram Navami': require('../../assets/images/upcoming_radha_rani.png'),
  'Savitri Pooja': require('../../assets/images/upcoming_durga.png'),
  'Sharad Navratri': require('../../assets/images/upcoming_durga.png'),
  'Sharad Purnima': require('../../assets/images/upcoming_radha_rani.png'),
  'Thaipusam': require('../../assets/images/upcoming_shiva.jpg'),
  'Vaisakhi': require('../../assets/images/upcoming_radha_rani.png'),
  'Vasant Panchami': require('../../assets/images/upcoming_durga.png'),
  'Vishwakarma Puja': require('../../assets/images/upcoming_radha_rani.png'),
};

export const getFestivalImage = (name: string) => {
  if (!name) return null;
  if (FESTIVAL_IMAGE_MAP[name]) return FESTIVAL_IMAGE_MAP[name];
  const key = Object.keys(FESTIVAL_IMAGE_MAP).find(k => name.includes(k) || k.includes(name));
  return key ? FESTIVAL_IMAGE_MAP[key] : null;
};
