"""Create temple metadata schema - 15 tables

Revision ID: 73971a594ce0
Revises: 
Create Date: 2026-08-15 15:23:59.073165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73971a594ce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', name='auditaction'), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deity', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('JYOTIRLINGA', 'SHAKTI_PEETH', 'CHAR_DHAM', 'DIVYA_DESAM', 'ISKCON', 'SIKH', 'SACRED', name='templecategory'), nullable=False),
    sa.Column('established_year', sa.String(length=100), nullable=True),
    sa.Column('entry_fee', sa.String(length=255), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=255), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_area', sa.String(length=255), nullable=True),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_state', sa.String(length=255), nullable=True),
    sa.Column('location_country', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temples_category'), 'temples', ['category'], unique=False)
    op.create_index(op.f('ix_temples_is_active'), 'temples', ['is_active'], unique=False)
    op.create_index(op.f('ix_temples_name'), 'temples', ['name'], unique=False)
    op.create_index(op.f('ix_temples_slug'), 'temples', ['slug'], unique=True)
    op.create_index(op.f('ix_temples_updated_at'), 'temples', ['updated_at'], unique=False)
    op.create_table('content_approval_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temple_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temple_aarti_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('time_start', sa.String(length=100), nullable=False),
    sa.Column('time_end', sa.String(length=100), nullable=True),
    sa.Column('session_type', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='sessiontype'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_aarti_sessions_temple_id'), 'temple_aarti_sessions', ['temple_id'], unique=False)
    op.create_table('temple_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.Enum('NAME_ALIAS', 'ID_ALIAS', 'KEYWORD', name='aliastype'), nullable=False),
    sa.Column('match_mode', sa.Enum('INCLUDES', 'WORD_BOUNDARY', name='matchmode'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_aliases_alias_text'), 'temple_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_temple_aliases_temple_id'), 'temple_aliases', ['temple_id'], unique=False)
    op.create_table('temple_coords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coord_type', sa.Enum('MAIN', 'GHAT', 'ENTRANCE', 'PARKING', name='coordtype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_coords_temple_id'), 'temple_coords', ['temple_id'], unique=False)
    op.create_table('temple_darshan_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('opening_time', sa.String(length=100), nullable=True),
    sa.Column('closing_time', sa.String(length=100), nullable=True),
    sa.Column('general_darshan', sa.Text(), nullable=True),
    sa.Column('vip_darshan', sa.Text(), nullable=True),
    sa.Column('seasonal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temple_id')
    )
    op.create_table('temple_facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('facility_key', sa.Enum('PARKING', 'LOCKER', 'PRASAD', 'DRINKING_WATER', 'RESTROOMS', 'SHOE_STAND', 'WHEELCHAIR', 'DHARAMSHALA', 'BHOJANALAYA', 'PUJA_BOOKING', 'MEDICAL_AID', 'MOBILE_DEPOSIT', 'TRANSPORT_ASSISTANCE', 'HAIR_TONSURING', 'HOLY_KUND', name='facilitykey'), nullable=False),
    sa.Column('custom_label', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temple_id', 'facility_key', name='uq_temple_facility')
    )
    op.create_index(op.f('ix_temple_facilities_temple_id'), 'temple_facilities', ['temple_id'], unique=False)
    op.create_table('temple_festivals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_rule', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_festivals_temple_id'), 'temple_festivals', ['temple_id'], unique=False)
    op.create_table('temple_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'LIVE_STREAM', 'GALLERY', name='mediatype'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_media_temple_id'), 'temple_media', ['temple_id'], unique=False)
    op.create_table('temple_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('mythological_significance', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('sacred_rituals', sa.Text(), nullable=True),
    sa.Column('pilgrimage_circuit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temple_id', 'language_code', name='uq_temple_metadata_lang')
    )
    op.create_index(op.f('ix_temple_metadata_temple_id'), 'temple_metadata', ['temple_id'], unique=False)
    op.create_table('temple_official_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('WEBSITE', 'HELPLINE', 'EMAIL', 'BOOKING_PORTAL', name='officiallinktype'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_official_links_temple_id'), 'temple_official_links', ['temple_id'], unique=False)
    op.create_table('temple_transport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('transport_type', sa.Enum('AIR', 'RAIL', 'BUS', 'ROAD', name='transporttype'), nullable=False),
    sa.Column('route_description', sa.Text(), nullable=False),
    sa.Column('nearest_hub_name', sa.String(length=255), nullable=False),
    sa.Column('distance_from_hub_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_transport_temple_id'), 'temple_transport', ['temple_id'], unique=False)
    op.create_table('temple_visitor_guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_visitor_guidelines_temple_id'), 'temple_visitor_guidelines', ['temple_id'], unique=False)
    op.create_table('temple_guideline_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guideline_id', sa.UUID(), nullable=False),
    sa.Column('point_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guideline_id'], ['temple_visitor_guidelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_guideline_points_guideline_id'), 'temple_guideline_points', ['guideline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temple_guideline_points_guideline_id'), table_name='temple_guideline_points')
    op.drop_table('temple_guideline_points')
    op.drop_index(op.f('ix_temple_visitor_guidelines_temple_id'), table_name='temple_visitor_guidelines')
    op.drop_table('temple_visitor_guidelines')
    op.drop_index(op.f('ix_temple_transport_temple_id'), table_name='temple_transport')
    op.drop_table('temple_transport')
    op.drop_index(op.f('ix_temple_official_links_temple_id'), table_name='temple_official_links')
    op.drop_table('temple_official_links')
    op.drop_index(op.f('ix_temple_metadata_temple_id'), table_name='temple_metadata')
    op.drop_table('temple_metadata')
    op.drop_index(op.f('ix_temple_media_temple_id'), table_name='temple_media')
    op.drop_table('temple_media')
    op.drop_index(op.f('ix_temple_festivals_temple_id'), table_name='temple_festivals')
    op.drop_table('temple_festivals')
    op.drop_index(op.f('ix_temple_facilities_temple_id'), table_name='temple_facilities')
    op.drop_table('temple_facilities')
    op.drop_table('temple_darshan_details')
    op.drop_index(op.f('ix_temple_coords_temple_id'), table_name='temple_coords')
    op.drop_table('temple_coords')
    op.drop_index(op.f('ix_temple_aliases_temple_id'), table_name='temple_aliases')
    op.drop_index(op.f('ix_temple_aliases_alias_text'), table_name='temple_aliases')
    op.drop_table('temple_aliases')
    op.drop_index(op.f('ix_temple_aarti_sessions_temple_id'), table_name='temple_aarti_sessions')
    op.drop_table('temple_aarti_sessions')
    op.drop_table('content_approval_queue')
    op.drop_index(op.f('ix_temples_updated_at'), table_name='temples')
    op.drop_index(op.f('ix_temples_slug'), table_name='temples')
    op.drop_index(op.f('ix_temples_name'), table_name='temples')
    op.drop_index(op.f('ix_temples_is_active'), table_name='temples')
    op.drop_index(op.f('ix_temples_category'), table_name='temples')
    op.drop_table('temples')
    op.drop_table('content_audit_log')
    # ### end Alembic commands ###
