import { Dimensions, Platform, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    display: 'flex',
    width: '100%',
    paddingTop: 8,
    paddingBottom: 0,
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  tabsWrapper: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  tabItem: {
    display: 'flex',
    paddingVertical: 16,
    paddingHorizontal: 0,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  tabText: { 
    fontSize: 18, 
    fontWeight: '600', 
    color: 'rgba(0, 0, 0, 0.40)',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  tabTextActive: { 
    color: '#9B4500', 
    fontWeight: '700',
  },
  activeTabIndicator: {
    width: 119,
    height: 3,
    position: 'absolute',
    bottom: -1,
    alignSelf: 'center',
    borderRadius: 99,
    backgroundColor: '#9B4500',
  },

  // Date Selector
  dateSelector: {
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 0,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
    alignSelf: 'stretch',
  },
  dateChevron: {
    display: 'flex',
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  dateInfoWrapper: {
    alignItems: 'center',
  },
  dateMainText: {
    color: '#311303',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
  },
  dateSubText: {
    color: '#8C7263',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
  },

  // Dynamic Tabs styling
  tabContent: { paddingTop: 8, backgroundColor: 'transparent' },
  sectionHeader: { 
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    marginLeft: 16, 
    marginBottom: 8, 
    marginTop: 16 
  },
  sectionHeaderAlert: {
    color: '#BA1A1A',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    marginLeft: 8,
  },
  
  card: {
    display: 'flex',
    paddingHorizontal: 16,
    paddingVertical: 2,
    flexDirection: 'column',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFE2D5',
    backgroundColor: '#FFF',
    shadowColor: '#8C4200',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  infoRow: { 
    display: 'flex',
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    alignSelf: 'stretch',
    paddingVertical: 14,
  },
  infoDivider: {
    height: 1,
    alignSelf: 'stretch',
    backgroundColor: '#FFE2D5',
  },
  infoLabel: { 
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  infoValue: { 
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },

  // Sun Moon Times
  sunMoonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#FFE2D5',
    alignSelf: 'stretch',
    gap: 1,
  },
  sunMoonItem: {
    flexBasis: '49%',
    flexGrow: 1,
    height: 72,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 16,
    backgroundColor: '#FFF',
  },
  sunMoonIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFE2D5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sunMoonMeta: {
    flex: 1,
  },
  sunMoonLabel: {
    color: '#8C7263',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 16,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  sunMoonValue: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  
  // Inauspicious times
  inauspiciousHeaderBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 16,
    marginBottom: 8,
    marginTop: 16,
  },
  alertIconBox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  natureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 9999,
  },
  natureDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 4,
  },
  natureText: {
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 15,
  },
  natureBadge_good: { 
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  natureDot_good: { backgroundColor: '#22C55E' },
  natureText_good: { color: '#15803D' },
  natureBadge_good_active: {
    paddingHorizontal: 13,
    paddingTop: 6,
    paddingBottom: 7.5,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  natureDot_good_active: { 
    width: 8, 
    height: 8, 
    borderRadius: 4, 
    backgroundColor: '#22C55E' 
  },
  natureText_good_active: { 
    color: '#15803D',
    fontSize: 11,
    lineHeight: 16.5,
  },
  natureBadge_neutral: { 
    backgroundColor: '#FFE2D5',
    borderWidth: 1,
    borderColor: 'rgba(224, 192, 175, 0.30)',
  },
  natureDot_neutral: { backgroundColor: '#584235' },
  natureText_neutral: { color: '#584235' },
  natureBadge_neutral_active: {
    paddingHorizontal: 13,
    paddingTop: 6,
    paddingBottom: 7.5,
    backgroundColor: '#FFE2D5',
    borderWidth: 1,
    borderColor: 'rgba(224, 192, 175, 0.60)',
  },
  natureDot_neutral_active: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#584235' },
  natureText_neutral_active: { color: '#584235', fontSize: 11, lineHeight: 16.5 },
  natureBadge_bad: { 
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FEE2E2',
  },
  natureDot_bad: { backgroundColor: '#EF4444' },
  natureText_bad: { color: '#B91C1C' },
  natureBadge_bad_active: {
    paddingHorizontal: 13,
    paddingTop: 6,
    paddingBottom: 7.5,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  natureDot_bad_active: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#EF4444' },
  natureText_bad_active: { color: '#B91C1C', fontSize: 11, lineHeight: 16.5 },
  inauspiciousRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    paddingVertical: 14,
    width: '100%',
  },
  inauspiciousLabel: { 
    color: '#93000A',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  inauspiciousValue: { 
    color: '#BA1A1A',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },

  // Choghadiya Section
  choghadiyaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  choghadiyaCard: {
    width: (SCREEN_WIDTH - 48) / 2,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(186, 26, 26, 0.10)',
    padding: 16,
    marginBottom: 16,
    shadowColor: '#8C4200',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  choghadiyaTitle: {
    color: '#311303',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
    marginBottom: 4,
  },
  choghadiyaTime: {
    color: '#8C7263',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 20,
    marginBottom: 10,
  },
  choghadiyaBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 9999,
  },
  choghadiyaBadgeGood: {
    backgroundColor: '#DCFCE7',
  },
  choghadiyaBadgeBad: {
    backgroundColor: '#FFDAD6',
  },
  choghadiyaBadgeTextGood: {
    color: '#15803D',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  choghadiyaBadgeTextBad: {
    color: '#BA1A1A',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },

  // Hora Timeline layout
  horaTimelineContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
    paddingBottom: 20,
    position: 'relative',
  },
  horaTimelineRow: {
    flexDirection: 'row',
  },
  horaTimelineCol: {
    width: 30,
    alignItems: 'center',
    marginRight: 10,
    zIndex: 1,
    position: 'relative',
  },
  horaTimelineLine: {
    width: 1,
    height: 68,
    position: 'absolute',
    top: 24,
    backgroundColor: '#E0C0AF',
    zIndex: -1,
  },
  horaTimelineLineActive: {
    width: 1,
    height: 121,
    position: 'absolute',
    top: 24,
    backgroundColor: '#E0C0AF',
    zIndex: -1,
  },
  horaTimelineDotInactive: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#D2C3BB',
    borderWidth: 4,
    borderColor: '#FFF8F6',
    marginTop: 4,
  },
  horaTimelineDotActiveOuter: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(153, 71, 0, 0.20)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
  },
  horaTimelineDotActiveMiddle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFF8F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horaTimelineDotActiveInner: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FF6B00',
  },
  horaContentCol: {
    flex: 1,
    paddingBottom: 24,
  },
  horaInactiveBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  horaInactiveInfo: {
    flexDirection: 'column',
  },
  horaInactiveTime: {
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 18,
    marginBottom: 6,
  },
  horaPlanetRowMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  horaPlanetLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  horaPlanetIcon: {
    width: 16.5,
    height: 16.5,
    marginRight: 8,
  },
  horaPlanetIconActive: {
    width: 16.667,
    height: 16.667,
    marginRight: 8,
    tintColor: '#FF7B00',
  },
  horaPlanetNameInactive: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 24,
  },
  horaPlanetNameActive: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 24,
  },
  horaActiveCard: {
    borderWidth: 2,
    borderColor: '#FF7B00',
    borderRadius: 12,
    backgroundColor: '#FFF',
    padding: 16,
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
  },
  horaActiveTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  horaActiveTitle: {
    color: '#FF7B00',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginRight: 8,
  },
  horaActiveNowBadge: {
    backgroundColor: '#FF7B00',
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignItems: 'center',
  },
  horaActiveNowText: {
    color: '#FFF',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 15,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  horaActiveTime: {
    color: '#FF7B00',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 18,
    marginBottom: 12,
  },

  // Planets
  planetsTabContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: 'transparent',
  },
  planetCardNew: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#8C4200',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  planetHeaderNew: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  planetHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  planetNameCol: {
    marginLeft: 8,
  },
  planetNameNew: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 16,
  },
  planetSanskritNew: {
    fontSize: 10,
    fontWeight: '600',
    color: '#8C7263',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  planetHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  planetSignNew: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
    marginRight: 6,
  },
  planetDegreeNew: {
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 11,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
  },
  planetDot: {
    width: 4,
    height: 4,
    flexShrink: 0,
    borderRadius: 9999,
    backgroundColor: '#E0C0AF',
    marginHorizontal: 6,
  },
  planetMotionNew: {
    color: '#994700',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 24,
    textTransform: 'uppercase',
  },
  planetMotionRetro: {
    color: '#BA1A1A',
  },
  planetDescBox: {
    backgroundColor: '#FFF8F6',
    borderLeftWidth: 3,
    borderLeftColor: '#E0C0AF',
    padding: 12,
    borderRadius: 6,
  },
  planetDescText: {
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22.75,
  },
  nodesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  nodeCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(224, 192, 175, 0.10)',
    padding: 16,
    width: (SCREEN_WIDTH - 44) / 2,
    shadowColor: '#8C4200',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  nodeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nodeName: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 20,
    marginLeft: 6,
  },
  nodeSignDegree: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 11,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 24,
  },
  nodeMeaning: {
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 9,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: -0.45,
    textTransform: 'uppercase',
  },
  celestialCard: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    alignSelf: 'stretch',
    backgroundColor: '#FDF1E9',
    borderRadius: 16,
    padding: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(153, 71, 0, 0.20)',
    shadowColor: '#8C4200',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  celestialIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#9B4500',
    justifyContent: 'center',
    alignItems: 'center',
  },
  celestialTextCol: {
    flex: 1,
  },
  celestialTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  celestialLabel: {
    color: '#994700',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 24,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  celestialTime: {
    fontSize: 10,
    fontWeight: '500',
    color: '#584235',
  },
  celestialTitle: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 24,
  },
  celestialDesc: {
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 19.25,
    marginBottom: 12,
  },
  celestialLink: {
    color: '#994700',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 20,
  },

  emptyText: { textAlign: 'center', color: '#8C7263', marginTop: 60, fontSize: 16, paddingHorizontal: 32 },

  // Temple Cross-Feature Banner
  templeBannerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFE2D5',
    shadowColor: '#8C4200',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  templeBannerIconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFE2D5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  templeBannerContent: {
    flex: 1,
  },
  templeBannerTitle: {
    color: '#311303',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 2,
  },
  templeBannerDesc: {
    color: '#584235',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
  },
});
